Fix: Handle triple quotes correctly
savoirfairelinux/vscode-bitbake pull request #100
Opened 2023-11-27 17:27 UTC by WilsonZiweiWang

This handles the highlighting for triple quotes when the highlighting from the embedded service is not available.
![image](https://github.com/savoirfairelinux/vscode-bitbake/assets/47988425/60d8c0c7-d029-4c09-b47f-f40e7c887374)

Issue: https://github.com/yoctoproject/vscode-bitbake/issues/3

2023-11-27 21:19 UTC, deribaucourt approved these changes
Could go into staging instead of staging-next

2023-11-28 02:36 UTC, idillon-sfl approved these changes

2023-11-28 14:36 UTC, deribaucourt requested changes
Rebase on staging-next

2023-11-28 15:03 UTC, deribaucourt approved these changes

2023-11-28 15:49 UTC, merged