Refactor: Add 'common' package
savoirfairelinux/vscode-bitbake pull request #40
Opened 2023-10-27 14:52 UTC by idillon-sfl

Just the base of a 'common' package. For now it only includes NotificationType.

2023-10-27 14:53 UTC, idillon-sfl commented
Sorry, I should have paid attention to the CI before putting it into review

2023-10-31 08:29 UTC, deribaucourt requested changes

2023-10-31 08:29 UTC, deribaucourt commented on common/tsconfig.json
> +    "outDir": "out",
Have you tested the debug configuration (breakpoints) and .vsix packaging (install and test)?
I didn't know about npm link, it looks useful.

We should use the same way of sharing code between this PR and my WIP https://github.com/savoirfairelinux/vscode-bitbake/pull/41

Let's figure this out on the next meeting :)

2023-10-31 08:29 UTC, deribaucourt commented on client/tsconfig.json
> +		{ "path": "../common" }
Other ideas to name the common code: common, shared or lib. I don't know which one is more standard.

2023-10-31 08:29 UTC, deribaucourt commented on package.json
> +		"postinstall": "cd server && npm install && cd ../client && npm install && cd ../common && npm install && cd .. && npm run link:common",
You also need to clean the out/ and node_modules folder in npm run clean

2023-10-31 08:29 UTC, deribaucourt commented on common/tsconfig.json
> +    "outDir": "out",
You should check:
- [ ]  adding jest __tests__ in the common package
- [ ]  adding a dependency in the common package.json, checking that debugging has it, as well as the .vsix
- [ ]  npm run clean removes all generated files and folders.
- [ ]  generated files are also gitignored
- [ ]  vsix package doesn't contain .ts files
- [ ] breakpoints in the common code get hit when debugging the server and the client
- [ ] vsix works properly once installed

2023-11-02 14:38 UTC, idillon-sfl commented
lets close this

2023-11-02 14:38 UTC, closed without merging