Change author, repo urls, license
savoirfairelinux/vscode-bitbake pull request #6
Opened 2023-09-27 14:34 UTC by WilsonZiweiWang

2023-09-27 14:43 UTC, deribaucourt requested changes
I think we should still credit the original author.

2023-09-27 14:43 UTC, deribaucourt commented on client/package.json
> +  "author": "savoirfairelinux",
Maybe we should credit both? "Eugen Wiens & Savoir-faire Linux"

2023-09-27 17:56 UTC, moh60 approved these changes
LGTM

2023-10-02 07:21 UTC, deribaucourt approved these changes

2023-10-02 14:18 UTC, merged